// micro-projects/ui-architecture-playground/mvvm-vue/src/components/TopBar.vue
<script setup>
// Верхняя панель: работа с досками, сиды, экспорт/импорт/сброс.
// Только проброска команд VM - логики нет.
const props = defineProps({ vm: { type: Object, required: true } });
defineEmits(['open-users']);
</script>

<template>
    <header class="top-bar">
        <select :value="props.vm.currentBoardId.value"
                @change="props.vm.currentBoardId.value = $event.target.value" class="input board-select">
            <option v-for="b in props.vm.boards.value" :key="b.id" :value="b.id">{{ b.name }}</option>
        </select>
        <button class="btn" @click="props.vm.createBoard()">+ Доска</button>
        <button class="btn" :disabled="!props.vm.currentBoard.value" @click="props.vm.renameBoard()">&#9998; Переименовать</button>
        <button class="btn danger" :disabled="!props.vm.currentBoard.value" @click="props.vm.deleteBoard()">&#128465; Удалить</button>

        <span class="divider"></span>

        <button class="btn" :disabled="!props.vm.currentBoard.value" title="Эпик + 5 задач с дедлайнами (проверка overdue)"
                @click="props.vm.seedTestEpic()">Тест-эпик &#129514;</button>
        <button class="btn" :disabled="!props.vm.currentBoard.value" title="10 случайных задач (40/30/30)"
                @click="props.vm.seedRandomTasks()">+ 10 задач</button>
        <button class="btn" :disabled="!props.vm.currentBoard.value" @click="props.vm.createEpic()">+ Эпик</button>

        <span class="divider"></span>

        <button class="btn" @click="props.vm.exportJson()">Экспорт JSON</button>
        <button class="btn" @click="props.vm.importJson()">Импорт</button>
        <button class="btn danger" @click="props.vm.resetAll()">Сброс всего</button>
        <button class="btn primary right" @click="$emit('open-users')">Пользователи</button>
    </header>
</template>

// frontend/ui-architecture-playground/fsd-react/src/widgets/top-bar/ui/top-bar.tsx
// ============================================================================
// TopBar - виджет верхней панели: доски, сиды, экспорт/импорт/сброс.
// Виджет в FSD - КОМПОЗИЦИЯ сущностей и фич для крупного блока экрана.
// Здесь только проброс команд наверх - логики нет (как TopBar.vue).
// ============================================================================

import type { Board } from '@/entities/board';

interface TopBarProps {
    boards: Board[];
    currentBoardId: string | null;

    onBoardSelect: (id: string) => void;
    onCreateBoard: () => void;
    onRenameBoard: () => void;
    onDeleteBoard: () => void;

    onSeedTestEpic: () => void;
    onSeedRandomTasks: () => void;
    onCreateEpic: () => void;

    onExportJson: () => void;
    onImportJson: () => void;
    onResetAll: () => void;

    onOpenUsers: () => void;
}

export function TopBar(props: TopBarProps) {
    const noBoard = props.currentBoardId === null;   // gherkin: без доски команды недоступны
    return (
        <header className="top-bar">
            <select
                className="input board-select"
                value={props.currentBoardId ?? ''}
                onChange={e => props.onBoardSelect(e.target.value)}
            >
                {props.boards.map(b => <option key={b.id} value={b.id}>{b.name}</option>)}
            </select>
            <button className="btn" onClick={props.onCreateBoard}>+ Доска</button>
            <button className="btn" disabled={noBoard} onClick={props.onRenameBoard}>✎ Переименовать</button>
            <button className="btn danger" disabled={noBoard} onClick={props.onDeleteBoard}>🗑 Удалить</button>

            <span className="divider" />

            {/* Подписи кнопок совпадают с Vue/Angular - e2e переносимы между версиями */}
            <button className="btn" disabled={noBoard}
                    title="Эпик + 5 задач с дедлайнами (проверка overdue)"
                    onClick={props.onSeedTestEpic}>
                Тест-эпик 🧪
            </button>
            <button className="btn" disabled={noBoard}
                    title="10 случайных задач (40/30/30)"
                    onClick={props.onSeedRandomTasks}>
                + 10 задач
            </button>
            <button className="btn" disabled={noBoard} onClick={props.onCreateEpic}>+ Эпик</button>

            <span className="divider" />

            <button className="btn" onClick={props.onExportJson}>Экспорт JSON</button>
            <button className="btn" onClick={props.onImportJson}>Импорт</button>
            <button className="btn danger" onClick={props.onResetAll}>Сброс всего</button>
            <button className="btn primary right" onClick={props.onOpenUsers}>Пользователи</button>
        </header>
    );
}
