// frontend/ui-architecture-playground/fsd-react/src/shared/ui/modal-shell.tsx
// ============================================================================
// ModalShell - общая оболочка оверлея (.overlay > .modal), как в Vue-версии.
// Клик по фону = отмена. Аналог ShowDialog() из C#.
// Это "ui-кирпичик" слоя shared: знает про CSS, не знает про домен.
// ============================================================================

import type { ReactNode } from 'react';

interface ModalShellProps {
    children: ReactNode;
    onCancel: () => void;
}

export function ModalShell({ children, onCancel }: ModalShellProps) {
    return (
        <div className="overlay" onClick={e => { if (e.target === e.currentTarget) onCancel(); }}>
            <div className="modal">{children}</div>
        </div>
    );
}

// frontend/ui-architecture-playground/mvvm-vue/src/components/ModalShell.vue
<script setup>
// ModalShell - общая оболочка оверлея. Единый приём: слот для содержимого,
// клик по фону = отмена. Аналог ShowDialog() из C#-версий.
defineEmits(['cancel']);
</script>

<template>
    <div class="overlay" @click.self="$emit('cancel')">
        <div class="modal">
            <slot/>
        </div>
    </div>
</template>
